name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger when pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH private key
      run: |
        # Create the .ssh directory if it doesn't exist
        mkdir -p ~/.ssh

        # Store the SSH private key from GitHub Secrets into the id_rsa file
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa

        # Secure the private key (chmod 600)
        chmod 600 ~/.ssh/id_rsa

        # Disable Strict Host Key Checking to avoid the 'Host key verification failed' error
        echo "Host *" > ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
    - name: Install NGINX on EC2 and deploy the website
      run: |
        echo "$ssh-private-key" > private_key.pem
        chmod 400 "private_key.pem"
        ssh -o StrictHostKeyChecking=no -tt -i ~/.ssh/id_rsa ubuntu@ec2-44-206-251-5.compute-1.amazonaws.com << 'EOF'
          # Install NGINX if not installed
          sudo apt-get update
          sudo apt-get install nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

          # Change the default index.html
          sudo rm -rf /var/www/html/*
          sudo git clone https://github.com/${{ github.repository }} /tmp/
          sudo cp /tmp/index.html /var/www/html/index.html
          sudo systemctl restart nginx
        EOF
