name: Trigger Jenkins Build

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    
jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        run: |
          curl -X POST http://34.243.225.11:8080/job/Deploy_nginx2/build \
          --user prem:11bb8bc10ad836d483cc768865e714fe6b

