name: Trigger Jenkins Build

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    
jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Jenkins Job
        run: |
          curl -X POST http://44.222.203.146:8080/job/Deploy-nginx/build \
          --user prem:11672be8b3cc19170886ec62b4a7a11900

